import { Alchemy, Network } from "alchemy-sdk";
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { configureChains } from 'wagmi';
import { arbitrum, celo, mainnet, optimism, polygon } from 'wagmi/chains';
import { alchemyProvider } from 'wagmi/providers/alchemy';
import { publicProvider } from 'wagmi/providers/public';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { RainbowKitProvider, lightTheme, Chain } from '@rainbow-me/rainbowkit';
import Link from 'next/link';
import Layout from '../components/Layout';


const config = {
  apiKey: "af5g-7TjtMgPomEDZmTciXXd_NaQz9sd",
  network: Network.ETH_MAINNET,
};
const alchemy = new Alchemy(config);

const Home = () => {
  const { chains } = configureChains(
    [mainnet, polygon, optimism, arbitrum],
    [
      alchemyProvider({ apiKey: "af5g-7TjtMgPomEDZmTciXXd_NaQz9sd", }),
      publicProvider(),
    ]
  );

  return (
    <RainbowKitProvider chains={chains} theme={lightTheme({
      accentColor: 'white',
      accentColorForeground: 'black',
      borderRadius: 'medium',
      overlayBlur: 'large',
      })} >
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
            content="Generated by @rainbow-me/create-rainbowkit"
            name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="">Bankless Advisor</a> + <a href="/form">data</a> +{' '}
          <a href="https://nextjs.org">defi</a>
        </h1>
        <ConnectButton
            chainStatus="icon"
            showBalance={{
              smallScreen: false,
              largeScreen: true,
            }}
          />
        <p className={styles.description}>
          Get paid to make defi better @ {' '}
          <a className={styles.description} href='/form'>forms.ba</a>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href='/form'>
            <h2>Bankless Advisor & Users &rarr;</h2>
            <p>Get compensated for info sold to Protocols</p>
          </a>

          <a className={styles.card} href="https://banklessadvisor.com">
            <h2>Bankless Advisor & Protocols &rarr;</h2>
            <p>We connect Defi protocols to their users persepctive</p>
          </a>

          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
          <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
            Made with your frens at 🌈 
          </a>
        </footer>
      </div>
    </RainbowKitProvider>
  );
};

export default Home;